# Generated by Django 3.0.4 on 2020-05-23 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0002_auto_20200522_0022'),
    ]

    operations = [
        migrations.AddField(
            model_name='switch',
            name='image',
            field=models.ImageField(null=True, upload_to='switches/images/'),
        ),
    ]
