# Generated by Django 3.0.4 on 2020-05-26 18:23

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('keyboard', '0004_auto_20200526_2314'),
    ]

    operations = [
        migrations.AddField(
            model_name='review',
            name='keyboard',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, to='keyboard.Keyboard'),
        ),
    ]
